{% set version = "2.1.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mrmre
  version: {{ version|replace("-", "_") }}

source:
  fn: mRMRe_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/mRMRe_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mRMRe/mRMRe_{{ version }}.tar.gz

  sha256: fe23c5c1e7b5b653e0358e98f25ebd8c0c74c6c871606d1b24cd02a5534181d4

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('c') }}        # [linux or osx and c_compiler == "toolchain_c"]
    - {{ compiler('cxx') }}      # [linux or osx and c_compiler == "toolchain_c"]
  host:
    - r-base
    - r-igraph
    - r-survival
  run:
    - libcxx                # [osx and c_compiler == "clang"]
    - llvm-openmp           # [osx and c_compiler == "clang"]
    - r-base
    - r-igraph
    - r-survival


test:
  commands:
    - $R -e "library('mRMRe')"  # [not win]
    - "\"%R%\" -e \"library('mRMRe')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/mRMRe/index.html
  license: Artistic-2.0
  summary: Computes mutual information matrices from continuous, categorical and survival variables,
    as well as feature selection with minimum redundancy, maximum relevance (mRMR) and
    a new ensemble mRMR technique.
  license_family: OTHER
extra:
   recipe-maintainers:
    - conda-forge/r
