{% set version = "2.1.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mrmre
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mRMRe_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mRMRe/mRMRe_{{ version }}.tar.gz
  sha256: 1d2c3b53a6ecfa61f4891e08114d6951ebb7a9830c934515406e180277339209

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-igraph                     # [build_platform != target_platform]
    - r-survival                   # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-igraph
    - r-survival
  run:
    - r-base
    - r-igraph
    - r-survival

test:
  commands:
    - $R -e "library('mRMRe')"           # [not win]
    - "\"%R%\" -e \"library('mRMRe')\""  # [win]

about:
  home: https://cran.r-project.org/package=mRMRe
  license: Artistic-2.0
  summary: Computes mutual information matrices from continuous, categorical and survival variables, as well as feature selection with minimum redundancy, maximum relevance (mRMR) and a new ensemble mRMR technique.
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
