# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GgL6vCO43NfN7+LBNqNHotX35iOCKB6Cg01GoVWiZk0nNM+BzlPIQLRZ1ze6WLZKB0qgpnj1xiQK7pqAPEou068p0H7qWrUPNjFavUQ7ZrRfCcdH+DMNOB1hgIiytL+PdokEXqvpEd/wbBM6NEI1y+ssptqrJBTvKZ8eTz3NLlMqYW/Qx6gfdxcyAHSjYvCUjkD6SUdAWDQvAqKR5tu7z02DbphXDr6onLo5x+AtH6m4D9daLyVbPTSvbiaGp2YO8E2hyC7JLXK85MiDhn51YILjgzsPelveF6vl1Ikav53Y9Pc5cAo6DBPDrDUrerVmZgQWuEOsbKc9/gzYragJLocF3rLbVuIQEG6AFrV/qsr/qtuF3LjVvPzjPEediCdA7oVN8kV5YOKmmc+CihQ16yW+9jLKzV2ifDf9YhfEqJriwal2lSPVCp/caeaS/huZZ4DfjOws32F1gxu6kPqnxTktRoHcK75ZjnZZxakZlXYVibiKbJ+HKmxCSqokMum8B1lUkAi9UQazk49xvEdkqJwrrvdz8QDaoF20+C/TR5Xs0AD1A8MKGOLrgyUNP1tkyY1udv3yYZuNopb3ehgg8WBJk6cPgeufl5MySsxOXvDrzZYkouvBDbnZ4/iin68we0uSZLO+x6uxXwbHRnny71O6LpA/H0iN3RjQqNxTNlY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml