travis:
  secure:
    BINSTAR_TOKEN: FmrxFgAFMVW0C8x9wqRD7jsodjZ0QKYj+dAGr8QTD1xhnj9fmNjoKrkHxJJYYqoly1ggGPqoUVmH8aop4UoyQY1+UFMX9FAbHNr5Rrsjc0mEd3HGXEemXESLNthQ+AkNmNt7AuqV5OeOmoOGURAz3otJICleLZHYV+KbOYPNnCADggimV9vr/z6hDR7abrduW9oo3+G9VRmNncEPE7qktEXtKusX+lxV6ttt8qh5fcbmoZm/7DEgOnCv8vaO6owNeCieMdltbwhO52t9DTTwqPdraqr7yOEvjcC4CZpQ7/CMeL3JjPctnOS1EI/q+s7lvy98Sb8VYXPEi5oL8zkZoZWErBHFQebqtbsrMvSiNuRHRGsPh3jLAWNiMeNgkDr7mNZbxjG/bjgOgKfLx+FHr1kK+/NlADmx3hb+lI6ZKXlt9rYQNgQ6nzB0EqApR+oJjCpv/zBLQzK5EXeth3CaxOl8fgdf5SR6jbAbC9s+NC6Wv8lX3RdzVfMulXHb3Z/hWOdivliDDlpHodxIWX2vl8kmi0m7olOdJFZsbrezkG9zy6pCECUBRzM21JEuLWkqO6MEyVl3BzeWsxWdqPA5BAbL1qqV+0Z+dOSLZYtQb/umlOXBHxAiRYOBBJwJKFtiW8vTAo4kj1ERhhxLt7gtnV0nxYfqAfo3eHaxwT8uHrg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
