appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: GgL6vCO43NfN7+LBNqNHotX35iOCKB6Cg01GoVWiZk0nNM+BzlPIQLRZ1ze6WLZKB0qgpnj1xiQK7pqAPEou068p0H7qWrUPNjFavUQ7ZrRfCcdH+DMNOB1hgIiytL+PdokEXqvpEd/wbBM6NEI1y+ssptqrJBTvKZ8eTz3NLlMqYW/Qx6gfdxcyAHSjYvCUjkD6SUdAWDQvAqKR5tu7z02DbphXDr6onLo5x+AtH6m4D9daLyVbPTSvbiaGp2YO8E2hyC7JLXK85MiDhn51YILjgzsPelveF6vl1Ikav53Y9Pc5cAo6DBPDrDUrerVmZgQWuEOsbKc9/gzYragJLocF3rLbVuIQEG6AFrV/qsr/qtuF3LjVvPzjPEediCdA7oVN8kV5YOKmmc+CihQ16yW+9jLKzV2ifDf9YhfEqJriwal2lSPVCp/caeaS/huZZ4DfjOws32F1gxu6kPqnxTktRoHcK75ZjnZZxakZlXYVibiKbJ+HKmxCSqokMum8B1lUkAi9UQazk49xvEdkqJwrrvdz8QDaoF20+C/TR5Xs0AD1A8MKGOLrgyUNP1tkyY1udv3yYZuNopb3ehgg8WBJk6cPgeufl5MySsxOXvDrzZYkouvBDbnZ4/iin68we0uSZLO+x6uxXwbHRnny71O6LpA/H0iN3RjQqNxTNlY=}
