travis:
  secure:
    BINSTAR_TOKEN: XZGrJg+RrSAGirsCb9psvepw83Laxfo1UWHCJWVR4x1gXLlv9u/rCJIslpJVBcJPyVmBVj8i7tLuAhFBu33keeOx3PWbGdCTtASIzOH+MEArRWh3rw6L5iTeRJqtPSv6PqSDGJ3tWnSGUYJzRdlSOQYNDkE+/5IZy1uxUhJk/8B2maDefYbuVZe+I4+HGmCtCQDL1/y8uyMmV4S1Vn539iP5K07IwGa5NvhOy6yNlAkwDOK82+3oG25W4mySNQMrTV7JnNb6s5iL2OaQ/eOksm47y3SxxuEfmsfRezEjv+nSy6dR5I5m5IIXlAFNrTa682SlQnlwkq3AlZmyDwPvm0TriaGHYbXeu00h4VEaxNtnMGCGMcqVyqdaX/fQIJYZbauIFrWdlpyz1IFinvXn60R2PkP8BWbyUj7q8TusKUQxf0CBo5AtNcKFzNA+uVMPOhmHYavArzP9MFq+otZPjp4fipdFUJflkwqwi2eRoaWG8F6vfpgsw8GOCRaNuqxP8FefjaBr5T8tuApPLatiIOzybeN4rXXtI6YZsTQfiFAMi20J67+aZJeBeSwzT7G6YMDx/RMC/ReLkV8ImUiHWpt+kTCZlCms5PyEmUEECULXscvfD8O5eMsLtwFAtVdif+89zUcRSSHRgCDaZZnmpgelXjNsQfs6DK3uLuKupY0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
